name: "Multi-Board-Builder"

## Trigger
on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

# Global version
env:
  REPO_URI: ${{ github.server_url }}/${{ github.repository }}

jobs:
  arduino-samd-package:
    runs-on: ubuntu-latest
    env:
      BUILD: "${{ github.repository_owner }}-samd-ard-${{ github.ref_name }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: arduino/ArduinoCore-samd
          path: ${{ env.BUILD }}

      - name: Debug
        run: |
          ls -alhF
