name: "Multi-Board-Builder"

## Trigger
on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

# Global version
env:
  VERSION: ${{ github.ref_name }}-${{ github.run_id }}
  REPO_URI: ${{ github.server_url }}/${{ github.repository }}

jobs:
  arduino-samd-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug
        run: |
          ls -alhF .github/workflows
